const MODULES = [
  'users',
  'parts',
  'suppliers',
  'supplier_prices',
  'customers',
  'customer_prices',
  'sales_orders',
  'purchase_orders',
  'containers',
  'purchase_receipts',
  'inventory',
  'audit_logs',
  'dashboard',
];

const ACTIONS = ['create', 'read', 'update', 'delete'];

const ROLE_PERMISSIONS = {
  Admin: {
    users: ['create', 'read', 'update', 'delete'],
    parts: ['create', 'read', 'update', 'delete'],
    suppliers: ['create', 'read', 'update', 'delete'],
    supplier_prices: ['create', 'read', 'update', 'delete'],
    customers: ['create', 'read', 'update', 'delete'],
    customer_prices: ['create', 'read', 'update', 'delete'],
    sales_orders: ['create', 'read', 'update', 'delete'],
    purchase_orders: ['create', 'read', 'update', 'delete'],
    containers: ['create', 'read', 'update', 'delete'],
    purchase_receipts: ['create', 'read', 'update', 'delete'],
    inventory: ['create', 'read', 'update', 'delete'],
    audit_logs: ['read'],
    dashboard: ['read'],
  },
  Sales: {
    parts: ['read'],
    customers: ['create', 'read', 'update', 'delete'],
    customer_prices: ['create', 'read', 'update', 'delete'],
    sales_orders: ['create', 'read', 'update', 'delete'],
    purchase_orders: ['read'],
    containers: ['read'],
    inventory: ['read'],
    dashboard: ['read'],
  },
  Purchasing: {
    parts: ['create', 'read', 'update', 'delete'],
    suppliers: ['create', 'read', 'update', 'delete'],
    supplier_prices: ['create', 'read', 'update', 'delete'],
    purchase_orders: ['create', 'read', 'update', 'delete'],
    containers: ['create', 'read', 'update', 'delete'],
    purchase_receipts: ['read'],
    inventory: ['read'],
    dashboard: ['read'],
  },
  Warehouse: {
    parts: ['read'],
    suppliers: ['read'],
    containers: ['read', 'update'],
    purchase_receipts: ['create', 'read', 'update', 'delete'],
    inventory: ['create', 'read', 'update', 'delete'],
    customers: ['read'],
    dashboard: ['read'],
  },
  Viewer: {
    parts: ['read'],
    suppliers: ['read'],
    supplier_prices: ['read'],
    customers: ['read'],
    customer_prices: ['read'],
    sales_orders: ['read'],
    purchase_orders: ['read'],
    containers: ['read'],
    purchase_receipts: ['read'],
    inventory: ['read'],
    dashboard: ['read'],
  },
};

module.exports = { MODULES, ACTIONS, ROLE_PERMISSIONS };
